-- Keymaps are automatically loaded on the VeryLazy event
-- Default LazyVim keymaps: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
--
-- Deliberately empty. This workstation runs stock Vim/LazyVim bindings in both
-- editors: the JetBrains IDEs get the same keys through IdeaVim (~/.ideavimrc,
-- see config/dotfiles.manifest), so every habit built here transfers. A
-- JetBrains-parity keymap that exists in only one of the two editors is a habit
-- that has to be unlearned later, so none are defined.
--
-- The keys that used to live here and their stock replacements:
--   move line/selection      <A-j> / <A-k>
--   duplicate line           yyp   (or :t. for a count)
--   delete line              dd
--   expand/shrink selection  <C-Space> / <BS>   (flash.nvim treesitter), or S
--   change case              vim-abolish coercions, see lua/plugins/abolish.lua
--   terminal                 <C-/>, <leader>ft (root dir), <leader>fT (cwd)
--   jump back / forward      <C-o> / <C-i>
--   rename symbol            <leader>cr
--
-- Note on <C-Space>: the tmux prefix is also Ctrl+Space, so inside tmux/workmux
-- press it twice (`bind C-Space send-prefix` passes the second one through), or
-- use S (Flash Treesitter), which labels every enclosing node at once instead of
-- stepping outward one at a time.
